### ISSUE TITLE
how do you use addLocalPackage?

### ISSUE THREAD

**Issue by ignacio82** [RevolutionAnalytics/miniCRAN#96]
I want to add a package I created to my miniCRAN repository. I tried the following:

```
addLocalPackage("MyPackage", paste0("file:///", "C:/Users/MyUser/Projects/MyPackage_0.1.7.zip"),
                paste0("file:///", "C:/Users/MyUser/Projects/minicran/miniCRAN"))
Error: dir.exists(file.path(pkgPath)) is not TRUE
addLocalPackage("MyPackage", paste0("file:///", "C:/Users/MyUser/Projects/MyPackage/"),
                paste0("file:///", "C:/Users/MyUser/Projects/minicran/miniCRAN", build = TRUE))
Error: dir.exists(file.path(pkgPath)) is not TRUE
```

What am I doing wrong?

**Comment by ignacio82** [comment]
Thanks!

**Comment by achubaty** [comment]
per above, `pkgPath` is the path to a directory containing the built package, not the filepath of the package itself.

```r
addLocalPackage("mypackage", file.path("//aaa.intra.admin.ch/Userhome$/BBB-01/X6666666/data/Documents/BBB/Adam/Adam/nachher/BBBRepo/src/contrib", file.path("//aaa.intra.admin.ch/Userhome$/BBB-01/X6666666/data/Documents/BBB/Adam/Adam/nachher", "BBBRepo")), type = "source", deps = TRUE)
```

However, I'm confused about why you are adding a package that is already in the repo into the repo.  If the file already exists in the repo, just rebuild the package index.

**Comment by AdamSzendrei** [comment]
I have created a local repository from the CRAN mirror and after that I copied my package ("mypackage") into the folder that was created by the makeRepo command. I wanted to store all of the packages at the same place, because I have to upload the whole folder into our server where we don't have internet access, that's why I copied the "mypackage" into the repository folder.
I wanted to add "mypackage" to the repository, becaue currently when I use available.packages(), it doesn't list the "mypackage" package. 
I would like to use the command on the server:

    install.packages("mypackage", repos = paste0("file:///","/var/opt/td/R/r_packages/install"), type = "source")

but since the "mypackage" is not listed as a available package, I cannot do that.

How can I add the "mypackage" to the repository with all of its dependency?

**Comment by achubaty** [comment]
In general, don't modify the repo contents "manually" (you shouldn't have to copy/paste at the OS / file browser level). Instead, use the miniCRAN functions as they will take care of copying the files and updating the package indices.

Did you run the command I included in my previous reply? Try that first. It will ensure the package index gets written correctly.

If for some reason that doesn't do the trick, rebuild the package index "manually":

```r
Rversion <- getRversion()
repoPath <- file.path("//aaa.intra.admin.ch/Userhome$/BBB-01/X6666666/data/Documents/BBB/Adam/Adam/nachher", "BBBRepo")
srcPath <- file.path(repoPath, miniCRAN:::repoPrefix("source", Rversion))
tools::write_PACKAGES(srcPath, type = "source")
```

**Comment by AdamSzendrei** [comment]
Now I copied the .tar.gz package into another directory and when I use that path for pkgPath it adds "mypackage" to the repository and it copies the file into the repository directory.

Sorry for bugging you with such a question, but based on the documentation and error message, I couldn't figure it out what the problem is.

Thanks!

**Comment by achubaty** [comment]
It could be that it's trying to move the file to where it already is (i.e., overwrite itself) which, of course, would fail.

**Comment by andrie** [comment]
@AdamSzendrei If you have suggestions on how we can improve the documentation, I'd love to hear. Based on your experience, there certainly is scope for improvement.

It will be ideal if you can create a pull request that include your suggested improvements.

Many thanks in advance

:-)

Andrie

**Comment by achubaty** [comment]
I agree, perhaps adding a check in that function so that if the "from" and "to" locations are the same it will fail gracefully or at least notify the user.
