### ISSUE TITLE
Install package from webserver instead of local drive?

### ISSUE THREAD

**Issue by ignacio82** [RevolutionAnalytics/miniCRAN#97]
I am able to install my own package using miniCRAN if i do the following:

```
install.packages("MyPackage", 
                 repos = paste0("file:///", pth),
                 type = "source")
```

But if I try to install it from my webserver instead, I get an error

```
install.packages("MyPackage", 
                 repos = "https://MYWEBSERVER.something/miniCRAN",
                 type = "source")

Installing package into ‘C:/Users/MyUser/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘MyPackage’ is not available (for R version 3.3.3)

```

My guess is that I need to specify something in my package because I have no troubles installing a package that I didn't create from my webserver

```
install.packages("foreach", 
                 repos = "https://MYWEBSERVER.something/miniCRAN",
                 type = "source")
```

Could you point me in the right direction to fix this? Thanks!

**Comment by achubaty** [comment]
you'll need to confirm that the webserver is setup up correctly:

0. is your webserver correctly configured to serve all files in the repo?
1. does the url https://MYWEBSERVER.something/miniCRAN contain the correct directory structure?
2. if you are using Windows to install your package, are the windows binaries available on the webserver?
3. since you didn't specify your R version, check that the same version is being used on the webserver and on your local machine. Binary packages exist in a versioned subdirectory.

**Comment by achubaty** [comment]
when you open https://MYWEBSERVER.something/miniCRAN in your browser, can you see the files for your package? is it present in the PACKAGES file?

**Comment by ignacio82** [comment]
0. Yes
1. Yes
2. Yes
3. I don't have R on my webserver. I just copied the miniCRAN repository folder there. I'm running R 3.3.3 on windows

```
$version.string
[1] "R version 3.3.3 (2017-03-06)"

$nickname
[1] "Another Canoe"
```

The bin folder has ` bin -> windows -> contrib -> 3.3 -> MYPackage.zip `

Given that I can install `foreach` from my webserver, I was guessing that i did something wrong with `MyPackage`. But, I can install it from my minicran if i point to my local drive instead of my webserver.

**Comment by achubaty** [comment]
are you installing from source or from the binary?

you say the binary file (.zip) is there, but your `install.packages(...)` specifies `type = "source"`

**Comment by ignacio82** [comment]
i tried source and binary. Neither works from the webserver, both work from my local drive.

**Comment by achubaty** [comment]
I added a step 4 above. Can you check the files on the webserver in a browser to confirm the package is there and it's linted in `PACKAGES`?

**Comment by ignacio82** [comment]
Yes, my package is listed in `PACKAGES`

**Comment by achubaty** [comment]
NOTE: given that it is working locally for you, this suggests an issue with the webserver rather than the `miniCRAN` package.

can you share the link to the webserver? you can email me directly if you don't want to make it public.
is your package source tarball and/or the binary zip downloadable form the server in your browser? how did you build the package before adding it to the miniCRAN locally (before copying over the whole miniCRAN repo to the webserver)?

**Comment by ignacio82** [comment]
Thanks @achubaty . I will send you an email with my server.

**Comment by achubaty** [comment]
@ignacio82 the following worked for me (I've substituted the actual server/package info with the dummy versions used above):

```r
myRepo <- "https://MYWEBSERVER.something/miniCRAN"
myPkg <- "MyPackage"
tmpDir <- file.path(tempdir(), "miniCRAN", "debug", "97") ## temp library location
dir.create(tmpDir, recursive = TRUE)

available.packages(repos = myRepo) ## shows the package
download.packages(myPkg, repos = myRepo, type = "source", destdir = tmpDir) ## works
install.packages(myPkg, repos = myRepo, type = "source", lib = tmpDir) ## works

unlink(tmpDir, recursive = TRUE)
```

Double check the spelling of your package.
